---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  test_repo_uri: https://github.com/hardening-io/tests-os-hardening.git
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-os-hardening/
  playbook: default.yml
  ansible_extra_flags:
    - "--skip-tags=sysctl"

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
- name: ubuntu-15.10
  driver:
    image: ubuntu:15.10
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    provision_command:
      - "apt-get install initramfs-tools -y"
- name: centos-6.6
  driver:
    image: centos:6.6
- name: centos-6.7
  driver:
    image: centos:6.7
- name: centos-7
  driver:
    image: centos:7
    privileged: true
    run_command: /usr/sbin/init
- name: debian-7
  driver:
    image: debian:7
- name: debian-8
  driver:
    image: debian:8
verifier:
  name: inspec
suites:
- name: os-ansible_1.9
  provisioner:
    ansible_version: 1.9.4
- name: os-ansible_latest
  provisioner:

